### PR TITLE
use Julia ReentrantLock rather than fftw_make_planner_threadsafe

### LINKED ISSUE #141: Deadlock with multiple FFTW plan construction / destruction in serial and threaded runs
Running the following code example causes a deadlock conjunction with Julia 1.3.1, DFTK 0.0.5 and FFTW 1.2.0. [Stacktrace](https://gist.github.com/mfherbst/4015ff891001597fccf66648abff1aa1) (after a Ctrl-C) indicates that the deadlock occurs in fftw. Notice, such behaviour is encountered both in serial and threaded runs.

Code example:
```
using DFTK    
    
function main()    
    for Ecut in 0.0 .+ collect(3:20)    
        println("Ecut = $Ecut")    
        a = 10.263141334305942    
        lattice = a / 2 .* [[0 1 1.]; [1 0 1.]; [1 1 0.]]    
        model = Model(lattice; terms=[Kinetic()], n_electrons=4)    
        basis = PlaneWaveBasis(model, Ecut)    
    end    
end    
    
main()   
```

Output / Stacktrace: https://gist.github.com/mfherbst/4015ff891001597fccf66648abff1aa1

Sorry about the complicated reproducer btw ... I tried to reduce as much as I could.

### PR DESCRIPTION
**Pull request by stevengj**
Should fix #141.  Closes #157.

### CODE REVIEW

**Comment by vtjnash** [comment]
This is a large portion of it, definitely! Though doesn't yet fix the deadlock. While this is a re-entrant lock, we shouldn't ever see it be re-entered from a given thread (whether on the same or a different task) as fftw doesn't like that. However, we might see that some `finalizer` tries to acquire this lock. To protect against that, the finalizers also need to be delayed until the unlock call here, to ensure that they destroy call doesn't get blocked.

**Comment by stevengj** [comment]
I don't quite follow you.  If a given thread holds the lock and FFTW is busy calling some thread-unsafe routine (e.g. creating or destroying a thread), how could a finalizer concurrently execute `fftw_destroy_plan` on the same thread?

File: src/FFTW.jl [hunk 1]
```diff
@@ -52,15 +52,41 @@ function __init__()
...
+# most FFTW calls other than fftw_execute should be protected by a lock to be thread-safe
+const fftwlock = ReentrantLock()
+
+# protect thread-safety of expressions or whole functions by fftwlock:
+macro exclusive(ex)
+    if Meta.isexpr(ex, :function) || (Meta.isexpr(ex, :(=)) && Meta.isexpr(ex.args[1], :call))
+        newbody = quote
+            try
+                lock(fftwlock)
+                $(esc(ex.args[2]))
```
Comment (vtjnash) [inline src/FFTW.jl:71]: For the sake of demonstration purposes only, consider all of the places we'll call `fftwf_destroy_plan` from, such as right here:
```suggestion
                GC.gc()
                $(esc(ex.args[2]))
```

For stress-testing, you actually want this in `spawnloop` though, since it's in that location that causes fftw to become deadlocked.

**Comment by stevengj** [comment]
I see, so the scenario we are worried about is something like:

1. User starts creating a plan in a thread.  Acquires lock.
2. FFTW planner, while exploring different algorithms, calls `spawnloop`.
3. During Julia `spawnloop` execution, one of the spawned threads runs GC and tries to destroy an old plan.  Deadlocks.

**Comment by stevengj** [comment]
Maybe when `fftwlock` is acquired, it should set a global flag that will cause all `destroy_plan` calls to be deferred to a queue, and that it can flush the queue right before it releases the lock?

That will get rid of all the business with a timer in #157, and allow garbage collection to function normally most of the time.

**Comment by vtjnash** [comment]
That sounds great

**Comment by stevengj** [comment]
Okay, I updated the thread to defer plan destruction while the lock is held.

(The plan-destruction queue itself requires a lock, and the logic of flushing the queue is a bit tricky to avoid deadlocks or race conditions, so I'd appreciate another pair of eyes to double-check my logic.)

File: src/fft.jl [hunk 2]
```diff
@@ -258,18 +257,70 @@ size(p::FFTWPlan) = p.sz
...
+        end
+    finally
+        unlock(deferred_destroy_lock)
+    end
+end
+
+@exclusive destroy_plan(plan::FFTWPlan) = unsafe_destroy_plan(plan)
+
+function maybe_destroy_plan(plan::FFTWPlan)
+    if trylock(fftwlock)
```
Comment (vtjnash) [inline src/fft.jl:300]: This is re-entrant, so I think this’ll succeed, while the internal lock inside destroy will hang

File: src/fft.jl [hunk 3]
```diff
@@ -258,18 +257,70 @@ size(p::FFTWPlan) = p.sz
...
+        try
+            unsafe_destroy_plan(plan)
+        finally
+            unlock(fftwlock)
+        end
+    else
+        try
+            lock(deferred_destroy_lock)
```
Comment (vtjnash) [inline src/fft.jl:308]: This lock needs to acquired first, so that another thread can’t release fftwlock and then skip past destroy_deferred before we get around to acquiring this lock

File: src/FFTW.jl [hunk 4]
```diff
@@ -52,15 +52,42 @@ function __init__()
...
+            finally
+                unlock(fftwlock)
+                destroy_deferred() # deallocate plans queued to be destroyed while we held the lock
```
Comment (vtjnash) [inline src/FFTW.jl:74]: Perhaps slightly cheaper to move this before the unlock, since we may try immediately to reacquire it?

File: src/fft.jl (hunk 2 above)
Comment (stevengj) [reply src/fft.jl:300]: Can I just use a non-reentrant lock?

File: src/FFTW.jl (hunk 4 above)
Comment (stevengj) [reply src/FFTW.jl:74]: I had that originally, but that creates a possible memory leak — we destroy_deferred, then another finalizer runs and defers destroy_plan, then we unlock, leaving a non-empty list of plans to destroy.

File: src/fft.jl (hunk 3 above)
Comment (stevengj) [reply src/fft.jl:308]: Right.

File: src/fft.jl (hunk 2 above)
Comment (stevengj) [reply src/fft.jl]: Kind of annoying that Julia doesn't provide a non-reentrant lock other than `SpinLock`.   I suppose I could set a flag of some sort in addition to the lock…

Comment (stevengj) [reply src/fft.jl]: (There is no internal lock inside `unsafe_destroy_plan` now that I've turned off `fftw_make_planner_threadsafe`; the danger is that it will mutate FFTW internal state in a way that will corrupt the running planner.)

Comment (stevengj) [reply src/fft.jl]: I pushed an update with a `trylock_nonreentrant` function that should fix this?

File: src/FFTW.jl [hunk 5]
```diff
@@ -52,15 +52,42 @@ function __init__()
...
 
+# most FFTW calls other than fftw_execute should be protected by a lock to be thread-safe
+const fftwlock = ReentrantLock()
+
+# protect thread-safety of expressions or whole functions by fftwlock:
+macro exclusive(ex)
+    if Meta.isexpr(ex, :function) || (Meta.isexpr(ex, :(=)) && Meta.isexpr(ex.args[1], :call))
+        newbody = quote
+            try
+                lock(fftwlock)
```
Comment (vtjnash) [inline src/FFTW.jl:70]: I think it's more common to switch the order of these try/lock calls (https://stackoverflow.com/a/10868476), though it shouldn't make a functional difference.

Comment (stevengj) [reply src/FFTW.jl:70]: Will do

**Comment by stevengj** [comment]
Now that I think of it, probably it is actually safe to use the regular `trylock` in `maybe_destroy_plan` — the FFTW planner is not thread-safe, but it *is* re-entrant (and in fact we call it recursively inside FFTW), and the same should be true for `destroy_plan`.

So, it should be fine to destroy a plan in the thread that acquired the planner lock, even if that occurs during planning.
